# Generated by Django 5.2.14 on 2026-05-07 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('READ', 'Retrieved'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('DOWNLOAD', 'Downloaded'), ('LOGIN', 'Logged In'), ('LOGIN_FAILED', 'Login Failed')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(help_text='Type of resource (e.g., Document, Authentication).', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource.', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address at the time of the action.')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client User-Agent header.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (filenames, hashes, etc.). Never store secrets.')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for failed logins).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'sentinel_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_audit_user_time'), models.Index(fields=['action', '-timestamp'], name='idx_audit_action_time'), models.Index(fields=['resource_type', 'resource_id'], name='idx_audit_resource')],
            },
        ),
    ]
