# Generated by Django 5.2.14 on 2026-05-07 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique document identifier (UUIDv4).', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Human-readable document title.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the document.')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('encrypted_file', models.FileField(help_text='Path to the Fernet-encrypted file on disk.', upload_to='encrypted_documents/')),
                ('file_hash', models.CharField(help_text='SHA-256 hex digest of the ORIGINAL (unencrypted) file.', max_length=64)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the original (unencrypted) file in bytes.')),
                ('content_type', models.CharField(help_text='MIME type of the original file (e.g., application/pdf).', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive documents are hidden from listings.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the document was first uploaded.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last metadata update.')),
                ('owner', models.ForeignKey(help_text='User who uploaded this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'sentinel_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['owner', '-uploaded_at'], name='idx_doc_owner_date'), models.Index(fields=['file_hash'], name='idx_doc_hash')],
            },
        ),
    ]
